# Generated by Django 4.2.1 on 2023-06-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_useraddress_address_alter_useraddress_address2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='post_code',
        ),
    ]
