# Generated by Django 4.2.1 on 2023-07-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_orderitem_cost_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
